### PR TITLE
add readonly as attribute to pikaday-input

### PR DESCRIPTION
**Pull request by DenizOkcu**
It would be great to have 'readonly' support for mobile devices:

```javascript
{{pikaday-input  readonly='readonly'}}
```

### CODE REVIEW

**Comment by stravid** [comment]
Thank you for your contribution @DenizOkcu! Unfortunately this change seems to break the test suite, can you investigate?

**Comment by DenizOkcu** [comment]
Hi @stravid, `npm test` fails even without my changes:
```
not ok 22 PhantomJS 1.9 - PikadayInputComponent: selecting a date should update the value attribute
```
and your code works as expected in my app. So I didn't do anything about it. I will take a deeper look when I come home from work though. Thanks for the quick reply.

**Comment by stravid** [comment]
You are totally right @DenizOkcu the test also fails locally for myself. Weird thing because the last time everything was green.

It will look myself for the cause of the failing test since it is obviously not your PR that causes it.

**Comment by stravid** [comment]
Sorry for the long silence, I got pretty sick. The tests are green again on master so now you can add tests for your own new behaviour :-)

**Comment by DenizOkcu** [comment]
Thanks for the fix. I added the readonly attribute and a test. I hope everything is ok. This is my first pull request :-)

**Comment by stravid** [comment]
I have to thank you for your contribution @DenizOkcu! I just updated the readme, changelog and published a new release with your addition :-)

**Pull request merged**
