### PR TITLE
Upgrade to the newest pikaday version

### PR DESCRIPTION
**Pull request by drapergeek**
This fixes bugs mentioned in #56.

The test suite goes green and in playing with in my own application I didn't see any bugs.

### CODE REVIEW

**Comment by drapergeek** [comment]
Any way we could get a review and possibly merge?

**Comment by stravid** [comment]
Sorry for the delayed review, it was not my intention to keep you waiting. Big thanks for the pull request and resolving the issue @drapergeek :-)

**Comment by stravid** [comment]
I just released and published `0.14.0` with your changes, thanks again for the contribution.

**Comment by drapergeek** [comment]
Thanks!

**Pull request merged**
