### PR TITLE
[Refactoring] DDAU paradigm, integration test and others

### PR DESCRIPTION
**Pull request by Fed03**
I've done several things in this PR:

- updated to ember-cli@2.4.3
- updated the component to use the DDAU paradigm:
    - data is passed to the component via the `value` attribute
    - an action is sent up via `onSelection=(action 'someAction')` carrying the just selected data
- I've ported all the unit tests to the component style integration tests
- Added a new functionality to pass an option hash overriding the default options passed to pikadate
- It's all compatible with ember 1.13+

### CODE REVIEW

**Comment by stravid** [comment]
Thank you so much for your contribution @Fed03! This looks very promising, can you please rebase on `master`? In the meanwhile I will take a closer look at the commits so we can get this merged.

**Comment by Fed03** [comment]
@stravid Rebased!

**Comment by alexgb** [comment]
We're looking for a date picker that supports DDAU. @stravid is this ready to merge? Anything we can do to help?

**Comment by stravid** [comment]
@alexgb from a functional standpoint this pull request is good to merge. The problem is the README, it needs an update to accurately reflect the new DDAU code base. If you want to help you can take care of this :) Would be the last thing in our way to a `2.0.0` release.

**Comment by Fed03** [comment]
@stravid look into the readme, I've updated something and documented the new features

**Comment by stravid** [comment]
@Fed03 I just published a beta release with the version `2.0.0-beta.1`. Thank you so much again for putting in all this work. And I'm sorry for keeping you waiting for so long :(

**Comment by Fed03** [comment]
@stravid no problem! We are all here to help each others. It's not work xd

**Pull request merged**
