### PR TITLE
Wire up position and reposition options

### PR DESCRIPTION
**Pull request by chrislopresto**

### CODE REVIEW

**Comment by stravid** [comment]
Thank you for your contribution @chrislopresto, please add tests for the newly introduced behaviour so we can merge this pull request.

**Comment by chrislopresto** [comment]
@stravid From a quick perusal of pikaday, I don't see anything easily testable. I believe the only effects triggered by setting the `position` and `reposition` properties are the calculated pixel values for `top` and `left` in the inline styles on the `pika-single` div. These are contingent upon location within the viewport and would probably make for brittle tests.

Any suggestions?

**Comment by stravid** [comment]
@chrislopresto sorry for the long delay, you are totally right. It seems to be nonsense to test this. Let me merge and release a new version.

**Comment by stravid** [comment]
Thank you again for your contribution, I just released version `1.1.` including your changes.

**Pull request merged**
