### PR TITLE
added theme option

### PR DESCRIPTION
**Pull request by DerToti**
pull request regarding this issue #14

### CODE REVIEW

**Comment by stravid** [comment]
Thanks for your pull request, please add relevant tests and update the readme!

**Comment by DerToti** [comment]
done with adding relevant tests and updating the readme. please review

**Comment by stravid** [comment]
Thanks for your work, two things:

1. You changed the Pikaday dependency to point straight to HEAD, I assume you did this because the `theme` option [was just added to Pikaday and there is no release yet](https://github.com/dbushell/Pikaday/blob/master/CHANGELOG.md). I don't think pointing straight to  HEAD is a good idea since it basically means we have no control over the dependency. So if a future Pikaday commit breaks something ember-pikaday will be also broken for new installs.

2. The tests are failing on Travis CI, I assume this has something to do with the bumped Pikaday version. We will have to investigate what's the issue there.

I would like to wait with merging your pull request until we can point the Pikaday dependency to a specific version and the tests are green again. What do you think?

**Comment by DerToti** [comment]
i knew it wasnt a good idea. so sure lets wait for the next version of pikaday

**Comment by stravid** [comment]
It took a while but Pikaday finally tagged a new release. I created a new pull request that is rebased on master based on your commits: https://github.com/edgycircle/ember-pikaday/pull/34

Thanks for your contribution @DerToti! The new `0.8.0` release of ember-pikaday includes all this.

**Comment by DerToti** [comment]
nice finally :+1:  :)

**Pull request closed without merging**
