### PR TITLE
Set min date

### PR DESCRIPTION
**Pull request by yanglang**
Sorry for the late reply @stravid, I've updated the unit tests and also added the support for set max date as well.

Let me know if there is anything else you want to to do. Cheers

### CODE REVIEW

**Comment by yanglang** [comment]
just realized it's failing on ember#release, will look into and update here when I can.

**Comment by stravid** [comment]
Don't be sorry, I totally understand that doing open source work requires time which we often don't have. Thank you so much for revisiting your PR and submitting a perfect one :-)

I especially like the simple tests, I doubt I would have come up with an equally elegant solution.

Regarding the Travis CI fail, feel free to look into it. I think the test syntax/setup changed with Ember 2. I don't think this is related to your code.

**Comment by stravid** [comment]
The test errors were not related to your pull request. I updated Ember CLI which in turn made all tests green. Thanks again for your great pull request @yanglang, I will release a new version shortly!

**Comment by stravid** [comment]
`0.12.0` is now published.

**Pull request merged**
