### PR TITLE
Replace Ember.K with JavaScript syntax

### PR DESCRIPTION
**Pull request by locks**
See https://github.com/emberjs/rfcs/pull/178 for rationale.

### CODE REVIEW

**Comment by duizendnegen** [comment]
Thanks @locks

**Comment by cibernox** [comment]
@duizendnegen Could you cut a new patch version? I'd like to remove the warning for `Ember.K`

🙇

**Comment by duizendnegen** [comment]
I can't, looping in @stravid

**Comment by stravid** [comment]
@cibernox @duizendnegen if someone can go through the pull requests / commits and update `CHANGELOG.md` accordingly it will be easy to cut a new release for me. Right now I can't tell what changed. For the future I suggest we follow my SOP of updating the changelog immediately after a pull request ist merged. This will prevent situations like this one.

**Comment by duizendnegen** [comment]
@stravid yep, good point.
I updated `CHANGELOG.md` and `package.json` preparing for a 2.2.1 release.

**Comment by stravid** [comment]
@duizendnegen thanks! I just published to NPM.

**Pull request merged**
