### PR TITLE
Issue 93: Pass format string to moment to avoid deprecation warning

### PR DESCRIPTION
**Pull request by mdentremont**
- New versions of moment desire a format string passed to the moment
  constructor

### CODE REVIEW

**Comment by mdentremont** [comment]
@stravid Thoughts?

**Comment by mdentremont** [comment]
@stravid Thoughts?

**Comment by mdentremont** [comment]
Oops

**Comment by mdentremont** [comment]
@stravid Thoughts?

**Comment by stravid** [comment]
Thanks for digging into this and providing a pull request @mdentremont! I will release a new release asap.

**Comment by stravid** [comment]
I just released `2.1.0` with your changes, thanks again!

**Pull request merged**
