### PR TITLE
Added the 'required' binding to allow use of html field validations.

### PR DESCRIPTION
**Pull request by TristanToye**
I needed this, so I added it.

If there was some reason it is not included I would be interested to know about it.

Cheers

### CODE REVIEW

**Comment by stravid** [comment]
Thanks for your contribution @TristanToye! Please add a test to prevent future regressions, once that's done I can merge.

If you are unsure how to do this give me heads up and I can walk you through.

**Comment by TristanToye** [comment]
Hey @stravid, I would appreciate some guidance on this - I haven't done much test writing in Ember yet.

**Comment by stravid** [comment]
Sure! In this case we don't want to the test the behaviour of "required" but rather if the binding works. (We can assume the browser implements require correctly.)

The `disabled` attribute is another example for such a case. You can find existing tests for this attribute here: https://github.com/edgycircle/ember-pikaday/blob/master/tests/unit/components/pikaday-input-test.js#L168-L180

We now need something similar for the `required` attribute in the same file. When using `ember serve` you can view the browser test runner under [http://localhost:4200/tests](http://localhost:4200/tests). `ember test` runs the tests in the terminal, whatever suits you better :)

**Comment by TristanToye** [comment]
Okay @stravid I think that should be what you needed! Sorry for the delay, busy busy. 

I didn't add anything beyond that it added the attribute - as the required attributes function is tied to the browser actions and not Ember.

**Comment by stravid** [comment]
Looks perfect, thank you for your contribution @TristanToye!

**Comment by stravid** [comment]
I just released and published `0.14.0` with your changes, thanks again for the contribution.

**Pull request merged**
