### PR TITLE
Bump ember-cli-moment-shim

### PR DESCRIPTION
**Pull request by jasonmit**

### CODE REVIEW

**Comment by stravid** [comment]
@jasonmit I could not find a changelog for your addon, could you give me a short summary what changed between the versions?

**Comment by stravid** [comment]
Any update @jasonmit?

**Comment by jasonmit** [comment]
The more significant of the changes is it pulls in moment/moment-timezone from npm instead of bower.  In >= 1.1.0, fastboot is supported.

**Comment by jasonmit** [comment]
cc @stravid

**Comment by stravid** [comment]
Thanks for the explanation @jasonmit!

**Pull request merged**
