### PR TITLE
Bump to 2.8

### PR DESCRIPTION
**Pull request by lan0**
While debugging an issue with 2.8 in our app (Pikaday somehow gets stuck in an endless loop while in `setDate()` called from `setupPikaday()`), I wanted to make sure this addon works so I bumped the dependencies.

Hopefully it passes on travis, since I changed the `travis.yml` according to the release notes...

### CODE REVIEW

**Comment by duizendnegen** [comment]
@lan0 merging in a few other PRs has caused conflicts, could you rebase?

**Comment by lan0** [comment]
Done!

The tests fail in pre-2.3 scenarios on PhantomJS 1.9 though.
On PhantomJS 2.1 it passes locally when I do `ember try:one ember-2.2.2 test`. Any ideas?

**Comment by lan0** [comment]
Reverting to globally install phantomjs on travis fixed the tests. It now uses PhantomJS 2.1 for all scenarios.

The offending test also failed on `master` with 1.9, so this shouldn't be a regression.

**Comment by duizendnegen** [comment]
Thanks - I know upgrading dependencies can be a chore, so I appreciate this being done!

**Pull request merged**
