### PR TITLE
Prepare for FastBoot 1.0

### LINKED ISSUE #155: Fix breaking changes in FastBoot 1.0
The current `ember-cli-fastboot` releases (1.0.0-rc.1 and above) introduce breaking changes. These will most likely break your current FastBoot implementation.

See https://github.com/ember-fastboot/ember-cli-fastboot/issues/387 for more information and a guide on how to fix your addon. Also you may want to visit the `-fastboot` Slack channel to get help from other users.

*Note: this issue has been created automatically, by searching for certain patterns in your code. If you think this has been falsely created, feel free to close!*

### PR DESCRIPTION
**Pull request by josemarluedke**
ember-fastboot/ember-cli-fastboot#387

Fixes #155.

### CODE REVIEW

**Comment by duizendnegen** [comment]
Thank you!

**Comment by josemarluedke** [comment]
@duizendnegen mind publishing a new version containing this change?

**Comment by duizendnegen** [comment]
@stravid mind doing an `npm publish`? I prepared the release in https://github.com/edgycircle/ember-pikaday/commit/0ae21fb98955c8396402244be63bf7b95dceb75d

(if you add me to the `npm` organisation, I can also do this without involving you next time)

**Comment by stravid** [comment]
Sorry, GitHub notifications don't catch my attention this much. What is your NPM username @duizendnegen?

**Comment by duizendnegen** [comment]
@stravid https://www.npmjs.com/~duizendnegen

**Comment by stravid** [comment]
Thanks, you should be a collaborator now. If you need me to do more, just tell me!

**Comment by duizendnegen** [comment]
`2.2.3` is now out 🎉

**Pull request merged**
