### PR TITLE
bind `disabled` and `placeholder`

### PR DESCRIPTION
**Pull request by leojpod**
Hi!

Thanks for the ember-addon! 

I quickly added a binding for `disabled` and `placeholder` as I needed it in my app. Works as expected: when disabled no pikadate calendar shows up.

Have a good day!

### CODE REVIEW

**Comment by stravid** [comment]
Hello Leo!

Thanks for your pull request, can you please add tests for the added functionality?
This helps us to prevent future breakage :-)

Thanks a lot! (If you need help getting started writing tests I'm all ears :-))

**Comment by leojpod** [comment]
Hi David,

I'm in a rush to push some code so I'll probably start looking at writing
tests for this next week :)

**Comment by stravid** [comment]
Any update @leojpod?

**Comment by leojpod** [comment]
Woops sorry I kinda totally forgotten about writing those tests. I'll try to get that done for good this week!

**Comment by leojpod** [comment]
Hi @stravid 

Here are the unit-tests! Sorry it took so long.

**Comment by polymathnyc** [comment]
@stravid any update on the PR? I'm happy to look into it if additional work is needed on the placeholder.

**Comment by stravid** [comment]
Thanks a lot for this @leojpod and having the foresight to handle the case where an already open datepicker gets disabled. I will release a new version on Monday containing your code.

**Comment by leojpod** [comment]
Great !
You are welcome.

**Pull request merged**
